<a href="https://colab.research.google.com/github/MirzaSerajBaig/automation/blob/main/Datascience_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("My name is Mirza seraj baig")

My name is Mirza seraj baig


In [ ]:
# comment

In [ ]:
#() method/function,tuples

In [ ]:
x=44500

In [ ]:
x

44500

In [ ]:
type(x)

int

In [ ]:
z="mirza"

In [ ]:
z=13.5

In [ ]:
type(z)

float

In [ ]:
20+10

30

In [ ]:
100-80

20

In [ ]:
990/99

10.0

In [ ]:
85*10

850

In [ ]:
import math

In [ ]:

math.sqrt(64)

8.0

In [ ]:

list1=["Bread",20,13.5,True]

In [ ]:
list1

['Bread', 20, 13.5, True]

In [ ]:
list1[1]

20

In [ ]:
list1[1]=40

In [ ]:
list1

['Bread', 40, 13.5, True]

In [ ]:



import math
round(4.5)

4

In [ ]:
name="Mirza seraj baig"
study="phd"
details=name + study
print(details)

Mirza seraj baigphd


In [ ]:
name="Mirza seraj baig"
study="phd"
details=name +" "+study
print(details)

Mirza seraj baig phd


In [ ]:
a=name="Mirza seraj baig"
study="phd"
a=10
str(a)
detail=name + study+ a
print(detail)

TypeError: can only concatenate str (not "int") to str

In [ ]:
a=name="Mirza seraj baig"
study="phd"
a="10"
type(a)
detail=name + study+" "+a
print(detail)

Mirza seraj baigphd 10


In [ ]:
a="Good Morning"
b="Mirza seraj baig"
a+b

'Good MorningMirza seraj baig'

In [ ]:
a+" "+b

'Good Morning Mirza seraj baig'

In [ ]:
3>5

False

In [ ]:
20<10

False

In [ ]:
8==7

False

In [ ]:
8!=7

True

In [ ]:
8<7

False

In [ ]:
8>=8

True

In [ ]:
20<=30

True

In [ ]:
test=4>1

In [ ]:
test

True

In [ ]:
type(test)

bool

In [ ]:

test=4>1

In [ ]:
test

True

In [ ]:
type(test)

bool

In [ ]:
test2=not (5>1)

In [ ]:
test2

False

In [ ]:
test or test2

True

In [ ]:
test3=6>7

In [ ]:

test4=10==11

In [ ]:
test4

False

In [ ]:
test3 or test4

False

In [ ]:
sample1=7>6

In [ ]:
sample1

True

In [ ]:
sample2=6>8

In [ ]:
sample2

False

In [ ]:
sample2 and sample1

False

In [ ]:
sample3=5>1
sample4=6>3
sample3 and sample4

True

In [ ]:
True or True

True

In [ ]:
while 5>2 :
  print("Hello")



Hello


NameError: name 'end' is not defined

In [ ]:
counter=0
while counter <=10:
  print(counter)
  counter=counter+1

print("Thanks counter and while loop")

0
1
2
3
4
5
6
7
8
9
10
Thanks counter and while loop


In [ ]:
i=0
while i<=10:
  print(i)
  i=i+1

print("loop completed")

0
1
2
3
4
5
6
7
8
9
10
loop completed


In [ ]:
i=0
while i<=10:
  print(i)
  i=i+1

  print("loop completed")

0
loop completed
1
loop completed
2
loop completed
3
loop completed
4
loop completed
5
loop completed
6
loop completed
7
loop completed
8
loop completed
9
loop completed
10
loop completed


In [ ]:
i=0
while i<=10:
  print(i)
  i=i+1
  print(f"{i} loop completed")

0
1 loop completed
1
2 loop completed
2
3 loop completed
3
4 loop completed
4
5 loop completed
5
6 loop completed
6
7 loop completed
7
8 loop completed
8
9 loop completed
9
10 loop completed
10
11 loop completed


In [ ]:
i=0
while i<=10:
  print(i)
  i=i+1
  print(f"{i-1} loop completed")

0
0 loop completed
1
1 loop completed
2
2 loop completed
3
3 loop completed
4
4 loop completed
5
5 loop completed
6
6 loop completed
7
7 loop completed
8
8 loop completed
9
9 loop completed
10
10 loop completed


In [ ]:
for i in range(6):
  print("hello python")

hello python
hello python
hello python
hello python
hello python
hello python


In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [ ]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [1]:
print("Hello")

Hello


In [3]:
for i in range(6):
  print(i)
print("prashant is fine")

0
1
2
3
4
5
prashant is fine


In [4]:
import numpy as np
from numpy.random import randn

In [10]:
x=randn()
if x>1:
  print("Greater than 1")
  result="Greater than one"
  print(x)
  print(result)
else :
  print("less than 1")

less than 1


In [11]:
x

0.511708569534965

In [14]:
result=None
x=randn()
if x>1:
  result="Greater than one"
print(x)
print(result)

1.3367089699564467
Greater than one


In [15]:
result=None
x=randn()
if x>1:
  result="Greater than one"
print(x)
print(result)

-0.08463879643311428
None


In [19]:
result=None
x=randn()
if x>1:
  result="Greater than one"
elif x<-1:
  result="less than one"
else:
  result="Between -1 and +1"
print(x)
print(result)

-0.15202513722445046
Between -1 and +1


In [20]:
import numpy as np
from numpy.random import randn,randint

In [22]:
result=None
x=randint(4)
if x>1:
  result="Greater than one"
elif x<-1:
  result="less than one"
else:
  result="Between -1 and +1"
print(x)
print(result)

2
Greater than one


In [23]:
List1=[11,9,6,45,76,89,1,4,18,23]

In [24]:
List2=["A","Hey",7,27.5,True]

In [25]:
type(List1)

list

In [27]:
list3=[List1,List2]

In [28]:
list3

[[11, 9, 6, 45, 76, 89, 1, 4, 18, 23], ['A', 'Hey', 7, 27.5, True]]

In [30]:
list5=range(5)

In [31]:
list5

range(0, 5)

In [34]:
list(range(5))

[0, 1, 2, 3, 4]

In [35]:
list(range(1,15))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [37]:
list(range(1,105,5))

[1,
 6,
 11,
 16,
 21,
 26,
 31,
 36,
 41,
 46,
 51,
 56,
 61,
 66,
 71,
 76,
 81,
 86,
 91,
 96,
 101]

In [38]:
list5[1]

1

In [40]:
l=["a","b","c","d","e"]


In [41]:
print(l)

['a', 'b', 'c', 'd', 'e']


In [42]:
l[0]

'a'

In [43]:
l[0]

'a'

In [45]:
l[-1]

'e'

In [46]:
l[2]

'c'

In [47]:
l

['a', 'b', 'c', 'd', 'e']

In [48]:
l2=list(range(20))

In [49]:
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [50]:
l2[2:7]

[2, 3, 4, 5, 6]

In [51]:
l2[-19]

1

In [52]:
l2[-8:-3]

[12, 13, 14, 15, 16]

In [53]:
l

['a', 'b', 'c', 'd', 'e']

In [54]:
l[1:5:2]

['b', 'd']

In [56]:
l[-1:-5:2]

[]

In [57]:
l[:]

['a', 'b', 'c', 'd', 'e']

In [60]:
l[:3]

['a', 'b', 'c']

In [61]:
l[3:]

['d', 'e']

In [62]:
l[::-1]

['e', 'd', 'c', 'b', 'a']

In [63]:
l[5:1:-1]

['e', 'd', 'c']

In [65]:
l[1:5:-1]

[]

In [66]:
1:18

SyntaxError: illegal target for annotation (<ipython-input-66-7cc8ce55e219>, line 1)

In [2]:
list1=[1,2,3,4,5,6]

In [3]:
list1

[1, 2, 3, 4, 5, 6]

In [4]:
type(list1)

list

In [6]:
list(range(1,51,3))

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [8]:
list2=list(range(1,51,3))

In [9]:
list2[2]

7

In [10]:
list[-49]

list[-49]

In [11]:
letter=["a","b","c","d","e","f","g","h","i","j"]

In [12]:
letter

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [13]:
letter[1:8:2]

['b', 'd', 'f', 'h']

In [14]:
letter[-9:-1:2]

['b', 'd', 'f', 'h']

In [15]:
letter[1:2]

['b']

In [16]:
letter[1::2]

['b', 'd', 'f', 'h', 'j']

In [17]:
letter[::3]

['a', 'd', 'g', 'j']

In [18]:
letter[:7]

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [19]:
letter[7:]

['h', 'i', 'j']

In [20]:
letter[::-1]

['j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [21]:
letter[1:6:-1]

[]

In [22]:
letter[6:1:-1]

['g', 'f', 'e', 'd', 'c']

In [23]:
tuple12=(12,36,72)

In [24]:
tuple12[1]

36

In [25]:
tuple12[1]=48

TypeError: 'tuple' object does not support item assignment

In [27]:
list12=[12,36,72]

In [28]:
list12[1]

36

In [29]:
list12[1]=48

In [30]:
list12

[12, 48, 72]

In [31]:
range(30,41)

range(30, 41)

In [32]:
list(range(30,41))

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

In [33]:
mylist=list(range(30,41))

In [34]:
print(mylist)

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


In [35]:
len(list(range(30,41)))

11

In [36]:
type(list(range(30,41)))

list

In [37]:
type(mylist)

list

In [38]:
max(mylist)

40

In [39]:
min(mylist)

30

In [41]:
max("Mirza seraj baig")

'z'

In [43]:
min("mirza")

'a'

In [44]:
len("mirzaseraj baig")

15

In [45]:
import numpy as np

In [46]:
list=[1,45,678,987,-1234]

In [47]:
a=np.array(list)

In [48]:
a

array([    1,    45,   678,   987, -1234])

In [50]:
type(a)

numpy.ndarray

In [51]:
list1=[1,45,678,987,-1234,98.3,"True","xyz"]

In [52]:
b=np.array(list1)

In [53]:
b

array(['1', '45', '678', '987', '-1234', '98.3', 'True', 'xyz'],
      dtype='<U32')

In [54]:
print(b)

['1' '45' '678' '987' '-1234' '98.3' 'True' 'xyz']


In [57]:
#Data hierachy>>string>>float>integer>bolean

In [3]:
import numpy as np

In [59]:
list5=["a",20,30.5,True]

In [60]:
np.array(list5)

array(['a', '20', '30.5', 'True'], dtype='<U32')

In [61]:
list6=[20,30.5,True]
np.array(list6)

array([20. , 30.5,  1. ])

In [62]:
list7=[20,True]
np.array(list7)

array([20,  1])

In [63]:
list8=[True]
np.array(list8)

array([ True])

In [4]:



b=np.array([2345,6789,9876,1456,-1234])

In [5]:
b.mean()

3846.4

In [6]:
b

array([ 2345,  6789,  9876,  1456, -1234])

In [7]:
b[::2]

array([ 2345,  9876, -1234])

In [8]:
c=b[2:4]

In [9]:
c

array([9876, 1456])

In [10]:
c[:]

array([9876, 1456])

In [11]:
c

array([9876, 1456])

In [15]:
b

array([ 2345,  6789,  9876,  1456, -1234])

In [13]:
#similar means likely not same

In [16]:
c[:]=222

In [14]:
#tupple immutable list

In [17]:
c

array([222, 222])

In [18]:
b


array([ 2345,  6789,   222,   222, -1234])

In [19]:
dict1={"Name":"Mirza","Age":28,"place":"bangalore","Country":"India"}

In [21]:
dict1

{'Name': 'Mirza', 'Age': 28, 'place': 'bangalore', 'Country': 'India'}

In [22]:
dict1["Name"]

'Mirza'

In [23]:
dict1["Age"]

28

In [24]:
dict2={"India":"I love my India","State":"bihar","birth":"Darbhanga","village":"dilawarpur"}

In [28]:
dict2

{'India': 'I love my India',
 'State': 'bihar',
 'birth': 'Darbhanga',
 'village': 'dilawarpur'}

In [27]:
dict2["India"]

'I love my India'

In [29]:
dict2['village']

'dilawarpur'

In [30]:
dict3={"index0":"emp no","index1":"emp name","index2":"salary","index3":"dept"}

In [31]:
dict3

{'index0': 'emp no',
 'index1': 'emp name',
 'index2': 'salary',
 'index3': 'dept'}

In [32]:
dict3["index2"]

'salary'